version: "3.8"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    image: proj-fe
    ports:
    - target: 5000
      published: 5000
  db:
    container_name: mysql
    build: ./database
    image: proj-db
    environment:
      DATABASE_URI: mysql+pymysql://root:password@mysql:3306/users
      SECRET_KEY: password
      MYSQL_ROOT_PASSWORD: password
  backend:
    container_name: backend
    build: ./backend
    image: proj-be
    depends_on:
      - "db"
    ports:
    - target: 5001
      published: 5001
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
